config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('main.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

main/urls.py
from django.urls import path
from .views import IndexView,AdSite
app_name = 'main'
urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('adsite/', AdSite.as_view(), name='adsite')
]

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logOut, name="logout"),
    path('signup_save/', views.signup_save, name='signup_save')
]

main/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from config import settings
from datetime import datetime


USER_TYPE = (
    ('Applicant', 'Applicant'),
    ('Employer', 'Employer'),
)

GENDER_SELECTION = (
    ('Male', 'Male'),
    ('Female', 'Female'),
)

LANGUAGES= (
    ('en', 'en'),
    ('ru', 'ru'),
    ('uz', 'uz'),
)

class CustomUser(AbstractUser):
    user_type= models.CharField(max_length=20, choices=USER_TYPE)
    phone = models.CharField(max_length=17, blank=True, null=True)
    telegram = models.CharField(max_length=150, blank=True, null=True)
    instagram = models.CharField(max_length=150, blank=True, null=True)
    website = models.CharField(max_length=150, blank=True, null=True)
    linkedin= models.CharField(max_length=150, blank=True, null=True)
    facebook = models.CharField(max_length=150, blank=True, null=True)
    github = models.CharField(max_length=150, blank=True, null=True)
    youtube = models.CharField(max_length=150, blank=True, null=True)
    about = models.TextField(blank=True)
    languages = models.CharField(max_length=20, choices=LANGUAGES, blank=True)
    gender = models.CharField(max_length=20, choices=GENDER_SELECTION, blank=True)
    avatar = models.ImageField(upload_to='avatars/', default='avatars/default.png', blank=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    
    class Meta:
        ordering = ['-date_joined']

    def __str__(self):
        return str(self.username)

main/views.py
from django.shortcuts import render
from django.views import View


# Create your views here.
class IndexView(View):
    def get(self, request):

        return render(request, 'pages/index.html')
    
class AdSite(View):
    def get(self, request):
        return render(request, 'pages/adsite.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.views import View
from django.shortcuts import get_object_or_404
from .models import CustomUser, USER_TYPE
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here..
def loginPage(request):
    user_type = USER_TYPE
    context = {
        'user_type':user_type
    }
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main:home')
            # if not user.first_name:
            #     messages.info(request,"Please enter your information")
            #     return redirect("users:profile", username)
                
        else:
            return messages.error("Username or password is incorrect")

    return render(request, 'users/login.html', context)


def logOut(request):
    logout(request)
    return redirect('users:login')


def signup_save(request):
    if request.method != "POST": 
        return HttpResponse("Method not allowed")
    else:
        user_type = request.POST.get("user_type")
        email = request.POST.get("email")
        username = request.POST.get("username")
        password = request.POST.get("password")
        password2 = request.POST.get("password2")
        telegram = request.POST.get("telegram")
        if password != password2:
            return messages.error("the password is not match!")
        else:
            try:
                user = CustomUser.objects.create_user(
                username=username,
                password=password,
                email=email,
                user_type = user_type,
                telegram = telegram
            )
                user.save()
                messages.success(request, "Registration successfully. You can login now!")
                return redirect(request.META.get("HTTP_REFERER"))
            except:
                messages.error(request, "Failed to Register")
                return redirect(request.META.get("HTTP_REFERER"))
        

templates/pages/adsite.html
{% extends 'pages/base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'assets/css/adsite.css' %}">
    {% block title %}Add site{% endblock title %}

    <div class="wrapper">
        <div class="intro container">
            <div class="intro_text">
                <h1>You are in the add site section</h1>
                
            </div>
            <div class="intro_img">
                <img src="{% static 'assets/img/sites-create-new.svg' %}" alt="">
            </div>
        </div>
        <div class="mega container">
            <div class="mega_text">
                <a href="#"><button type="button"><b>add site</b></button></a>
            </div>
            <div class="mega_text">
                <h1>List of your sites</h1>
            </div>
            <div class="mega_text">
                <a href="https://context.reverso.net/"><b>https://context.reverso.net/</b></a>
            </div>
            <div class="mega_text">
                <a href="https://context.reverso.net/"><b>https://context.reverso.net/</b></a>
            </div>
            <div class="mega_text">
                <a href="https://context.reverso.net/"><b>https://context.reverso.net/</b></a>
            </div>
            <div class="mega_text">
                <a href="https://context.reverso.net/"><b>https://context.reverso.net/</b></a>
            </div>
            <div class="mega_text">
                <a href="https://context.reverso.net/"><b>https://context.reverso.net/</b></a>
            </div>
            <div class="mega_text">
                <a href="https://context.reverso.net/"><b>https://context.reverso.net/</b></a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/pages/anadvertiser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/advents.css">
    <title>Register</title>
</head>
<body>
    <div class="wrapper">
        <div class="container">
            <input type="checkbox" id="check">
            <div class="login form">
              <header>Login</header>
              <form action="#">
                <input type="text" placeholder="Enter your email">
                <input type="password" placeholder="Enter your password">
                <a href="#">Forgot password?</a>
                <input type="button" class="button" value="Login">
              </form>
              <div class="signup">
                <span class="signup">Don't have an account?
                 <label for="check">Signup</label>
                </span>
              </div>
            </div>
            <div class="registration form">
              <header>Signup</header>
              <form action="#">
                <input type="text" placeholder="Enter your email">
                <input type="password" placeholder="Create a password">
                <input type="password" placeholder="Confirm your password">
                <input type="text" placeholder="Telegram">
                <input type="button" class="button" value="Signup">
              </form>
              <div class="signup">
                <span class="signup">Already have an account?
                 <label for="check">Login</label>
                </span>
              </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/pages/balance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/balance.css">
    
    <title>Document</title>
</head>
<body>
    <div class="wrapper">
    <div class="container">
           <header>
       
        <nav class="container">
            <div class="logo">
            <a href="index.html"><img src="./img/LOgo.jpg" alt=""></a></div>
            <ul class="menu">
            <li><a href="./index.html">Home</a></li>
            <li><a href="./reklamajoylashtirish.html">place an ad</a></li>
            <li><a href="./balance.html">balance</a></li>
            <li><a href="./adsite.html">Add site</a></li>
            <li><a href="#">Statistics</a></li>
            <li><a href="#">withdraw money</a></li>
            </ul>
        </nav>
    </header>
    </div>
    <div class="intro container">
        <div class="intro_text">
            <h1>You can see your balance here</h1>
            <p>Why do we pay money is a question that everyone asks.
                You have placed your site and placed our advertisement on it. If a user clicks on the advertisement on your site and enters the site, we will pay accordingly. Our minimum deposit is $10. When the funds in your account reach $10, we will contact you and send you the money. We will deliver</p>
        </div>
        <div class="intro_img">
            <img src="./img/331927-1024x682-man-holding-two-dollor-bills-1314996010.jpg" alt="">
        </div>
    </div>
    <div class="mega container">
        <div class="mega_text">
            <h1>Your balance</h1>
        </div>
        <div class="mega_balans">
            <h1>0.030$</h1>
        </div>
    </div>
    <div class="tolov container">
        <div class="tolov_text">
            <h1>Payment methods</h1>
        </div>
        <div class="tolov_img">
           <img src="./img/visa-payment-card1873.jpg" alt="">
        </div>
        <div class="tolov_img">
            <img src="./img/system-mastercard_c.png" alt="">
        </div>
        <div class="tolov_img">
            <img src="./img/payme-logo.svg" alt="">
        </div>
    </div>
</div>
</body>
</html>

templates/pages/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<div class="container">
    <header>

 <nav class="container">
     <div class="logo">
     <a href="index.html"><img src="{% static 'assets/img/LOgo.jpg' %}" alt=""></a></div>
     <ul class="menu">
         {% if user.is_authenticated %}
     <li><a href="{% url 'main:home' %}">Home</a></li>
     <li><a href="./reklamajoylashtirish.html">place an ad</a></li>
     <li><a href="./balance.html">balance</a></li>
     <li><a href="{% url 'main:adsite' %}">Add site</a></li>
     <li><a href="#">Statistics</a></li>
     <li><a href="#">withdraw money</a></li>
     <li><a href="{% url 'users:logout' %}">Logout</a></li>
     {% else %}
     <li><a href="{% url 'users:login' %}">Login</a></li>
     <li><a href="#">Signup</a></li>
     {% endif %}
     </ul>
 </nav>
</header>
</div>
{% block content %}{% endblock content %}
</body>
</html>

templates/pages/index.html
{% extends 'pages/base.html' %}]
{% load static %}
{% block title %}RekUz.com{% endblock title %}
{% block content %}
    <div class="wrapper">
        <div class="intro container">
            <div class="intro_img">
                <img src="{% static 'assets/img/reklama.png' %}" alt="" width="500px">
            </div>
            <div class="intro_text">
                <h1>Welcome</h1>
                <p>Welcome to our site and increase your income with us</p>
                <h2>There are all kinds of ads</h2>
                <a href="./anadvertiser.html"><button type="button"><b>an advertiser</b></button></a>
                <a href="./publisher.html"><button type="button"><b>publisher</b></button></a>
            </div>
        </div>
        <div class="border container">
            <div class="border_text">
                <img src="{% static 'assets/img/Free-Social-Media-Banner-Design-Flat-Style-scaled.jpg' %}" alt="">
                <h1>Banner</h1>
                <p>Banner ads look like this</p>
                <h2>Earn Big with Banner Ads You get paid more for banner ads. Earn money by placing ads on your site</h2>
            </div>
            <div class="border_text">
                <img src="{% static 'assets/img/podpiska-na-push-uvedomleniia.webp' %}" alt="">
                <h1>Push notification </h1>
                <p>push ads look like this</p>
                <h2>Earn Big with Push Ads You get paid more for banner ads. Earn money by placing ads on your site</h2>
            </div>
            <div class="border_text">
                <img src="{% static 'assets/img/digital-marketing-banner-template_23-2148924871.avif' %}" alt="">
                <h1>pro banner</h1>
                <p>pro banner  ads look like this</p>
                <h2>Pro banner ad appears in the front window of the site Appears in the front window when the user is using the site, and when the user clicks on the ad, you are paid.</h2>
            </div>
        </div>
    </div>
    {% endblock content %}

templates/pages/reklamajoylashtirish.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/reklamajoylashtirish.css">
    <title>place an ad</title>
</head>
<body>
    <div class="wrapper">
        <div class="container">
               <header>
           
            <nav class="container">
                <div class="logo">
                <a href="index.html"><img src="./img/LOgo.jpg" alt=""></a></div>
                <ul class="menu">
                <li><a href="./index.html">Home</a></li>
                <li><a href="./reklamajoylashtirish.html">place an ad</a></li>
                <li><a href="./balance.html">balance</a></li>
                <li><a href="./adsite.html">Add site</a></li>
                <li><a href="#">Statistics</a></li>
                <li><a href="#">withdraw money</a></li>
                </ul>
            </nav>
        </header>
        <div class="intro">
            <div class="intor_text">
                <div class="intro_text">
                    <h1>Hello, you are in the advertising section, you can post your own ads in this section...</h1>
                </div>
            </div>
                <div class="intro_img">
                    <img src="./img/banner-ad-examples-1024x536.jpg" alt="">
                </div>
            
        </div>
        <div class="rek">
            <div class="rek_text">
                <h1>Your sites</h1>
            </div>
            <div class="introo_text">
                <a href="#"><h2>file:///C:/Users/99899/Desktop/</h2></a>
                <a href="#"><Button type="button">Turn off</Button></a>
                <a href="#"><button type="button">advertise</button></a>
                <a href="#"><h2>https://www.google.com/</h2></a>
                <a href="#"><Button type="button">Turn off</Button></a>
                <a href="#"><button type="button">advertise</button></a>
                <a href="#"><h2>https://www.google.com/</h2></a>
                <a href="#"><Button type="button">Turn off</Button></a>
                <a href="#"><button type="button">advertise</button></a>
            </div>
        </div>
        </div>
</body>
</html>

templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'assets/css/publisher.css' %}">
    <title>Login</title>
</head>
<body>
    <div class="wrapper">
        <div class="container">
            <input type="checkbox" id="check">
            <div class="login form">
              <header>Login</header>
              <form action="#" method='POST'>
                {% csrf_token %}
                <input type="text" placeholder="Enter your username" name='username'>
                <input type="password" placeholder="Enter your password" name='password'>
                <a href="#">Forgot password?</a>
                <input type="submit" class="button" value="Login">
                {% if messages %}
                  <ul class="messages">
                      {% for message in messages %}
                      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                      {% endfor %}
                  </ul>
                {% endif %}
              </form>
              <div class="signup">
                <span class="signup">Don't have an account?
                 <label for="check">Signup</label>
                </span>
              </div>
            </div>
            <div class="registration form">
              <header>Signup</header>
              <form action="{% url 'users:signup_save' %}", method='POST'>
                {% csrf_token %}
                <div class="user-select" style="width:200px;">
                <select>
                  {% for type in user_type %}
                  <option>{{type}}</option>
                  {% endfor %}
                </select>
              </div>  
                <input type="text" name='email' placeholder="Enter your email">
                <input type="text" name='username' placeholder="Enter your username">
                <input type="password" name='password' placeholder="Create a password">
                <input type="password" name='password2' placeholder="Confirm your password">
                <input type="text" name='telegram' placeholder="Telegram">
                <input type="submit" class="button" value="Signup">
              </form>
              {% if messages %}
              <ul class="messages">
                  {% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                  {% endfor %}
              </ul>
            {% endif %}
              <div class="signup">
                <span class="signup">Already have an account?
                 <label for="check">Login</label>
                </span>
              </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/users/publisher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/publisher.css">
    <title>Login</title>
</head>
<body>
    <div class="wrapper">
        <div class="container">
            <input type="checkbox" id="check">
            <div class="login form">
              <header>Login</header>
              <form action="#">
                <input type="text" placeholder="Enter your email">
                <input type="password" placeholder="Enter your password">
                <a href="#">Forgot password?</a>
                <input type="button" class="button" value="Login">
              </form>
              <div class="signup">
                <span class="signup">Don't have an account?
                 <label for="check">Signup</label>
                </span>
              </div>
            </div>
            <div class="registration form">
              <header>Signup</header>
              <form action="#">
                <input type="text" placeholder="Enter your email">
                <input type="password" placeholder="Create a password">
                <input type="password" placeholder="Confirm your password">
                <input type="text" placeholder="Telegram">
                <input type="button" class="button" value="Signup">
              </form>
              <div class="signup">
                <span class="signup">Already have an account?
                 <label for="check">Login</label>
                </span>
              </div>
            </div>
        </div>
    </div>
</body>
</html>